---
layout: cv
title: Reiden Johnson's CV
---
# Reiden Johnson
Computer Information Technology | Cybersecurity

<div id="webaddress">
<a href="mailto:reidenjohnson@gmail.com">reidenjohnson@gmail.com</a>
| <a href="https://linkedin.com/in/reidenjohnson">LinkedIn</a>
| <a href="https://reidenjohnson.github.io/datascience_portfolio/resume.pdf">Download PDF</a>
</div>


## Currently

Senior at BYU-Idaho with a focus on data, systems, and general IT.


### Specialized in

Python, SQL, data analysis, Linux systems, APIs, and system troubleshooting


### Research interests

Understanding how systems work, improving efficiency, and solving real-world technical problems


## Education

`2020 - 2026`
__Brigham Young University - Idaho__

- B.S. Computer Information Technology
- Minor in Russian


## Awards

`2026`
AWS Certified Cloud Practitioner

`2020 - 2026`
Russian Language & Cultural Studies


## Publications

### Journals

`2026`
SQL-Spender – Python and SQLite expense tracker

`2026`
NetflixNavigator – Data analysis project using Pandas


### Patents

`2026`
CurConvert – JavaScript currency converter using APIs


<!-- ### Footer

Last updated: May 2013 -->